name: Static analysis

on:
    push:
        branches:
            - master

    pull_request_target:
        types: [ opened, synchronize ]

jobs:
    phpstan:
        runs-on: ubuntu-latest
        name: Check code style
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 10

            -   name: Install PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: none
                    php-version: "8.2"
                    tools: cs2pr

            - name: Install Composer dependencies
              uses: ramsey/composer-install@v2
              with:
                  # Bust the cache at least once a month - output format: YYYY-MM.
                  custom-cache-suffix: $(date -u "+%Y-%m")

            -   name: Run phpstan
                run: vendor/bin/phpstan analyse src/ -c vendor/solido/php-coding-standards/phpstan.neon --level=9 --no-progress -vvv --memory-limit=2048M --error-format=checkstyle 2> /dev/null | cs2pr
